export const SKILLS_BY_EXPERIENCE: Record<string, string[]> = {
  fresher: [
    "Cold Outbound (Email/Phone)",
    "Lead Research & Sourcing",
    "LinkedIn Sales Navigator",
    "CRM Hygiene (Salesforce/HubSpot)",
    "Objection Handling",
    "Discovery Call Basics",
    "Time Management",
    "Ideal Customer Profile Identification",
    "BDR/SDR Workflow",
    "Active Listening",
  ],
  mid: [
    "SaaS Product Demoing",
    "MEDDIC / MEDDPICC Methodology",
    "Solution Selling",
    "Pipeline Forecasting",
    "ROI & Business Case Mapping",
    "Multi-threading",
    "Contract Negotiation",
    "Account Mapping",
    "Gap Analysis",
    "Competitive Intelligence",
  ],
  senior: [
    "Enterprise Account Planning",
    "C-Suite Stakeholder Management",
    "Complex Deal Orchestration",
    "Strategic Global Partnerships",
    "TCO (Total Cost of Ownership) Modeling",
    "Territory Management & Strategy",
    "Value-Based Selling",
    "Sales Engineering Collaboration",
    "Change Management Selling",
    "Account-Based Marketing (ABM)",
  ],
  leadership: [
    "GTM (Go-to-Market) Strategy",
    "Revenue Operations (RevOps)",
    "Sales Playbook Development",
    "Compensation Plan Design",
    "Sales Recruitment & Training",
    "P&L Responsibility",
    "Executive Relationship Building",
    "Sales Mentorship & Coaching",
    "Sales Tech Stack Optimization",
    "Scaling High-Performance Teams",
  ],
};
