-- Unbiased Psychometric Questions Seed Script
-- Experience Band: Leadership (10+ Years)
-- Drivers: Burnout Risk, Growth Potential, Sales DNA
-- Implementation: Intent-based rubrics for Gemini 1.5 Flash evaluation

-- ------------------------------------------------------------------------------------------------
-- 1. BURNOUT RISK (EASY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'burnout_risk', 'leadership', 'low', 'Tell me about sustaining energy across long-term responsibilities.', 'Score 6: Masterful pacing. Candidate describes energy as a strategic resource managed through delegation, discipline, and intentional recovery cycles.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'Describe handling pressure at senior levels.', 'Score 6: Executive composure. Candidate views pressure as a systemic constant and explains techniques for maintaining personal and team stability under fire.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'How do you maintain balance under high accountability?', 'Score 6: Integrated life-design. Candidate describes clear boundaries and prioritizes well-being as a requirement for high-level decision making.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'Tell me about managing fatigue over time.', 'Score 6: Longitudinal health mindset. Candidate describes proactive monitoring of their mental and physical energy to prevent "slow-leak" exhaustion.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'Describe coping with organizational demands.', 'Score 6: Strategic filter. Candidate explains how they distinguish between "urgent noise" and "critical impact" to protect their mental bandwidth.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'How do you stay engaged after years of responsibility?', 'Score 6: Mission-driven persistence. Candidate connects their daily effort to a legacy or long-term vision that keeps the work intrinsically meaningful.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'Tell me about managing leadership stress.', 'Score 6: Role-modeling resilience. Candidate describes processing stress in a way that doesn''t leak into the organization, maintaining a calm environment.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'Describe maintaining clarity during complex decisions.', 'Score 6: Mental simplification. Candidate uses frameworks or advisors to strip away noise and focus on the fundamental logic of the decision.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'How do you recover after prolonged high-stakes cycles?', 'Score 6: Ritualized recovery. Candidate has a defined process for "switching off"—ensuring deep rest to return with full cognitive capacity.'),
('psychometric', 'burnout_risk', 'leadership', 'low', 'Tell me about balancing legacy and performance expectations.', 'Score 6: Sage perspective. Candidate shows they can deliver current results without compromising the long-term health or culture of the organization.');

-- ------------------------------------------------------------------------------------------------
-- 2. BURNOUT RISK (MEDIUM - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Tell me about cumulative stress across your career.', 'Score 6: Narrative wisdom. Candidate describes how they learned from past stress-peaks to build a "resilience engine" that handles 10x the load today.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Describe navigating emotional resilience fluctuations.', 'Score 6: EQ self-governance. Candidate recognizes their own emotional "weather" and adjusts their leadership intensity or visibility accordingly.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'How do you prevent accountability from becoming isolating?', 'Score 6: Mentorship and peer networks. Candidate describes building a "safe harbor" of peers or mentors to share the mental load of top-level responsibility.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Tell me about managing sustained strategic pressure.', 'Score 6: Endurance logic. Candidate describes viewing strategy as a marathon, using data and small wins to maintain momentum through years-long projects.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Describe maintaining enthusiasm after decades of performance.', 'Score 6: Constant reinvention. Candidate stays fresh by seeking new problems to solve or new technologies to master, preventing role-stagnation.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'How do you protect well-being under long-term expectations?', 'Score 6: Sustainable high-performance. Candidate argues that well-being is the *enabler* of expectations, showing evidence of a balanced lifestyle.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Tell me about handling decision fatigue at senior levels.', 'Score 6: Decision architecture. Candidate limits low-stakes decisions (delegation) to save their cognitive energy for the 5-10 choices that define the year.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Describe staying adaptable despite accumulated stress.', 'Score 6: Anti-fragility. Candidate shows how stress has made them *more* adaptable, using past crises as a library of responses for new challenges.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'How do you maintain engagement in high-responsibility roles?', 'Score 6: Multiplier mindset. Candidate finds engagement in seeing their *organization* grow, moving beyond personal ego toward collective success.'),
('psychometric', 'burnout_risk', 'leadership', 'medium', 'Tell me about managing long-term professional strain.', 'Score 6: Philosophical detachment. Candidate uses a high-level perspective to keep strain in context, preventing it from overwhelming their personal identity.');

-- ------------------------------------------------------------------------------------------------
-- 3. BURNOUT RISK (HARD - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Tell me about experiencing burnout at a senior stage.', 'Score 6: Radical candor and recovery. A vulnerable account of reaching the limit and the systemic changes made to their leadership philosophy to return stronger.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Describe handling emotional detachment from prolonged responsibility.', 'Score 6: Intentional reconnection. Candidate recognizes when they are "going on autopilot" and describes active steps to reconnect with people and purpose.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'How do you sustain identity and purpose under continuous pressure?', 'Score 6: Core values alignment. Candidate has a "North Star" that is independent of their job title, allowing them to remain stable even when work is chaotic.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Tell me about navigating chronic high-performance expectations.', 'Score 6: Expectation negotiation. Candidate describes the art of "managing up" to ensure expectations are ambitious but realistic for the organization''s health.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Describe rebuilding resilience after long-term exhaustion.', 'Score 6: Structural redesign. Candidate shares a moment of exhaustion that led to a "total reboot" of their operating system—new routines, new delegation, new mindset.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'How do you prevent career fatigue from affecting strategic thinking?', 'Score 6: Cognitive conservation. Candidate describes taking "strategy retreats" or sabbaticals to refresh their vision, ensuring they don''t lead from a place of depletion.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Tell me about your most challenging extended pressure cycle.', 'Score 6: Grit-led legacy. A story of a multi-year crisis (e.g., turnaround or merger) where they held the line and the personal cost they managed to pay and recover from.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Describe coping with declining energy while maintaining standards.', 'Score 6: Efficiency mastery. Candidate describes working "less but better"—using their 20 years of experience to solve in 1 hour what used to take 10.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'How do you ensure long-term engagement despite cumulative stress?', 'Score 6: Future-oriented logic. Candidate treats the organization as a living entity they are nurturing, finding energy in the growth of the next generation of leaders.'),
('psychometric', 'burnout_risk', 'leadership', 'hard', 'Tell me about safeguarding well-being across decades of leadership.', 'Score 6: Holistic longevity. Candidate describes their "Life Portfolio"—ensuring health, family, and hobbies are weighted alongside career for total stability.');

-- ------------------------------------------------------------------------------------------------
-- 4. GROWTH POTENTIAL (EASY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'growth_potential', 'leadership', 'low', 'Tell me about sustaining growth across decades of experience.', 'Score 6: Compound learning. Candidate treats growth as a daily habit, describing how they integrate new information into their existing deep wisdom.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'Describe adapting to industry evolution.', 'Score 6: Trend sensitivity. Candidate describes a recent shift in their industry and exactly how they updated their mental model to stay ahead of it.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'How do you maintain curiosity at senior levels?', 'Score 6: Open-minded exploration. Candidate describes seeking out "anti-experience"—talking to startups or junior explorers to challenge their own assumptions.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'Tell me about expanding your leadership impact.', 'Score 6: Influence expansion. Candidate describes moving from leading a function to leading an ecosystem, showing a desire to solve larger societal or industry problems.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'Describe investing in long-term capability building.', 'Score 6: Strategic upskilling. Candidate identifies a skill (e.g., AI ethics or Geopolitics) they are building *now* for relevance in the 2030s.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'How do you remain relevant in changing markets?', 'Score 6: Dynamic adaptation. Candidate treats their relevance as a "perpetual beta," constantly auditing and updating their skill set.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'Tell me about mentoring while continuing to grow.', 'Score 6: Reciprocal learning. Candidate describes a "reverse mentoring" scenario where they learn from the youth while providing the wisdom of experience.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'Describe adapting to technological disruption.', 'Score 6: Rapid tech adoption. Candidate shows they aren''t resistant to new tools but are leading the charge in learning how to leverage them for the business.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'How do you stay open to new perspectives?', 'Score 6: Intellectual humility. Candidate admits what they don''t know and describes creating "dissenting groups" in meetings to hear alternative views.'),
('psychometric', 'growth_potential', 'leadership', 'low', 'Tell me about broadening strategic influence.', 'Score 6: Ecosystem leadership. Candidate describes acting as a thought leader outside their company, influencing industry standards or policy.');

-- ------------------------------------------------------------------------------------------------
-- 5. GROWTH POTENTIAL (MEDIUM - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'growth_potential', 'leadership', 'medium', 'Tell me about reshaping your leadership style over time.', 'Score 6: Style evolution. Candidate describes a specific shift (e.g., from Command to Empowerment) prompted by a changing work world and their own self-reflection.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'Describe sustaining innovation despite experience depth.', 'Score 6: Destructive curiosity. Candidate shows they are willing to "kill" their own successful legacy models to make room for a new, better innovative approach.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'How do you identify emerging competencies required for the future?', 'Score 6: Environmental scanning. Candidate describes using cross-industry analogies to predict what their field will need in 5 years.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'Tell me about leading while simultaneously learning.', 'Score 6: Vulnerable leadership. Candidate describes leading a project in a field they were still learning, relying on their core logic while upskilling daily.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'Describe staying agile during economic or market disruption.', 'Score 6: Crisis agility. Candidate shows how they used a downturn as a "learning laboratory" to find new efficiencies and growth vectors.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'How do you challenge established thinking patterns?', 'Score 6: First-principles thinking. Candidate describes a time they asked "Why?" until the legacy logic broke, leading to a major breakthrough.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'Tell me about evolving beyond legacy success models.', 'Score 6: Post-legacy mindset. Candidate admits that what worked in 2010 won''t work in 2026 and describes the process of "unlearning."'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'Describe balancing legacy wisdom with new-age adaptability.', 'Score 6: Hybrid intelligence. Candidate explains when to use "Timeless Principles" and when to use "Modern Methods," showing a nuanced middle ground.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'How do you prepare the next generation while upgrading yourself?', 'Score 6: Parallel growth. Candidate describes a growth culture where they grow *with* their team, sharing lessons and failures in real-time.'),
('psychometric', 'growth_potential', 'leadership', 'medium', 'Tell me about reinventing strategic priorities.', 'Score 6: Strategic pivot logic. Candidate describes the data and "gut feel" process they used to realize the old strategy was dead and a new path was needed.');

-- ------------------------------------------------------------------------------------------------
-- 6. GROWTH POTENTIAL (HARD - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'growth_potential', 'leadership', 'hard', 'Tell me about redefining your long-term strategic direction.', 'Score 6: Visionary pivot. A story of shifting a whole company or career in a new direction based on a deep insight into the future, despite high risk.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'Describe leading adaptation during industry shifts.', 'Score 6: Industry-level leadership. Candidate describes how they guided not just their team, but their clients and patterns through a tectonic shift (e.g., Cloud or AI).'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'How do you make growth decisions when the long-term future is unclear?', 'Score 6: Probabilistic growth. Candidate uses "Small Bets" and rapid feedback loops to learn their way into the future rather than gambling.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'Tell me about navigating transformation while sustaining relevance.', 'Score 6: Ship-steadying. Candidate shows they can keep the current engine running (relevance) while simultaneously building the next engine (transformation).'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'Describe reshaping organizational culture to align with future strategy.', 'Score 6: Cultural architect. Candidate describes the difficult psychological work of changing "How we do things" to enable a new growth path.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'How do you handle resistance while driving innovation?', 'Score 6: Empathetic influence. Candidate treats resistance as data, addressing the "fear of loss" to bring people along on the growth journey.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'Tell me about exiting a legacy approach to adopt emerging models.', 'Score 6: Courageous exit. A story of walking away from a profitable but "stagnant" path to go all-in on an emerging, higher-potential future.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'Describe sustaining adaptability across decades.', 'Score 6: Longitudinal Agility. Candidate portrays adaptability not as a skill but as a *state of being* maintained through constant curiosity and travel/exposure.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'How do you build succession-ready leaders while evolving yourself?', 'Score 6: Generative leadership. Candidate believes their greatest growth is in creating leaders who are smarter and more agile than themselves.'),
('psychometric', 'growth_potential', 'leadership', 'hard', 'Tell me about your toughest strategic growth pivot.', 'Score 6: Masterclass in Strategy. A deep-dive into a high-stakes moment where they were wrong, realized it, and steered into a new success.'),

-- ------------------------------------------------------------------------------------------------
-- 7. SALES DNA (EASY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'sales_dna', 'leadership', 'low', 'Tell me about sustaining high performance across decades.', 'Score 6: Revenue resilience. Candidate describes a system-based approach to sales that survives market cycles and personal fluctuations.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'Describe maintaining strong client networks long-term.', 'Score 6: Social capital logic. Candidate treats relationships as "multi-year investments," focusing on value provided outside of the transaction.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'How do you adapt to changing buyer behavior?', 'Score 6: Psychological agility. Candidate recognizes the shift (e.g., from Logic-based to Outcome-based) and modifies their storytelling accordingly.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'Tell me about mentoring future sales leaders.', 'Score 6: Talent architecture. Candidate describes identifying "The Sales Spark" in others and building a process to scale it across a team.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'Describe balancing legacy clients with new acquisition.', 'Score 6: Portfolio logic. Candidate manages their "Hunter" and "Farmer" activities with mathematical precision to ensure both growth and stability.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'How do you stay competitive in evolving markets?', 'Score 6: Competitive intelligence. Candidate describes a habit of studying not just their product, but the *entire value chain* to find a superior angle.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'Tell me about managing long-term revenue accountability.', 'Score 6: Enterprise ownership. Candidate treats the P&L as their own, showing a deep sense of responsibility to the company''s bottom line.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'Describe sustaining motivation at senior levels.', 'Score 6: Purpose-led revenue. Candidate finds motivation in "Solving the Industry Problem" rather than just hitting a number.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'How do you maintain strategic influence in sales discussions?', 'Score 6: Peer-of-the-CEO. Candidate described being seen as a strategic advisor who happens to sell a solution, rather than a vendor.'),
('psychometric', 'sales_dna', 'leadership', 'low', 'Tell me about evolving your selling style over time.', 'Score 6: Style maturity. Candidate describes moving from "Persuasion" to "Facilitation"—helping the client navigate their own internal complexity to buy.');

-- ------------------------------------------------------------------------------------------------
-- 8. SALES DNA (MEDIUM - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'sales_dna', 'leadership', 'medium', 'Tell me about reshaping sales strategy during economic shifts.', 'Score 6: Strategic redirection. Candidate describes a time they moved a whole team from "Growth" to "Risk Mitigation" (or vice versa) to match the economy.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'Describe influencing board-level revenue discussions.', 'Score 6: Executive communication. Candidate explains how they translate "Sales Activity" into "Shareholder Value" for Board members.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'How do you align long-term growth with short-term revenue goals?', 'Score 6: Ambiguity management. Candidate describes the "Balancing Act" of hitting the quarter while investing in the 2-year ecosystem.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'Tell me about navigating large-scale account transitions.', 'Score 6: Multi-national orchestration. Candidate describes managing a "Global Account" through a change in leadership or merger, protecting the revenue.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'Describe managing sustained high-stakes negotiations.', 'Score 6: Master negotiator. Candidate describes a multi-month negotiation with extreme pressure, showing how they maintained logic and "Walk-away" points.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'How do you build succession-ready sales teams?', 'Score 6: Legacy sales management. Candidate hires and trains for *adaptability* and *values*, ensuring the team thrives even after they leave.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'Tell me about maintaining resilience during global downturns.', 'Score 6: Composure under crisis. Candidate describes holding their team and clients together during a period where "nobody is buying," finding the pivot.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'Describe repositioning offerings during industry change.', 'Score 6: Value-prop innovation. Candidate shows they can find the "New Pain" in a changing industry and map their solution to it faster than competitors.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'How do you sustain authority in competitive ecosystems?', 'Score 6: Thought leadership. Candidate builds authority by contributing to the category, not just their company, becoming a "Go-to expert" for the niche.'),
('psychometric', 'sales_dna', 'leadership', 'medium', 'Tell me about adapting to digital transformation in sales.', 'Score 6: Digital native mindset. Candidate describes moving from "Face-to-Face" to "Data-Led, Multi-Channel" selling without losing the human touch.');

-- ------------------------------------------------------------------------------------------------
-- 9. SALES DNA (HARD - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('psychometric', 'sales_dna', 'leadership', 'hard', 'Tell me about redefining revenue strategy in uncertain markets.', 'Score 6: Strategic foresight. A story of making a "contrarian bet" on a revenue source that others ignored, which became the primary growth driver.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'Describe leading sales adaptation during industry collapse.', 'Score 6: Crisis leadership. A "War Story" of keeping a revenue engine alive while an industry was being disrupted or regulated out of existence.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'How do you make high-risk revenue decisions when the future is unclear?', 'Score 6: Risk-Intelligence. Candidate describes the logical framework they use to "Bet the farm" on a new territory or model while protecting the base.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'Tell me about navigating global economic crises in sales leadership.', 'Score 6: Global resilience. Candidate describes managing revenue across multiple timezones and currencies during a systemic shock (e.g., 2008 or 2020).'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'Describe reshaping sales culture to align with future strategy.', 'Score 6: Cultural catalyst. Candidate describes the "Pain and Gain" of changing a team''s core motivation (e.g., from commission-focused to customer-success-focused).'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'How do you handle radical transformation resistance in sales teams?', 'Score 6: Influence and resolve. Candidate describes "Managing out" the legacy mindset while "Scaling up" the new-age performers during a transition.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'Tell me about exiting a legacy sales model to adopt innovation.', 'Score 6: Creative destruction. A story of shutting down a high-revenue but "poisonous" sales tactic to build a more sustainable, high-integrity future.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'Describe sustaining adaptability across decades in revenue roles.', 'Score 6: Longitudinal Agility. Candidate portrays their career as a series of "successful deaths" and "pivotal births"—constantly evolving with the market.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'How do you build succession-ready adaptive sales leaders?', 'Score 6: Mentorship legacy. Candidate believes their success is measured by the number of their proteges who are now VPs of Sales at other elite companies.'),
('psychometric', 'sales_dna', 'leadership', 'hard', 'Tell me about your toughest strategic revenue pivot.', 'Score 6: Masterclass in Turnaround. A deep-dive into a total revenue failure that they analyzed, pivoted, and turned into a massive success through logic and grit.');
