-- Unbiased Behavioral Questions Seed Script
-- Experience Band: Leadership (10+ Years)
-- Drivers: Resilience, Communication, Adaptability
-- Implementation: Intent-based rubrics for Gemini 1.5 Flash evaluation

-- ------------------------------------------------------------------------------------------------
-- 1. RESILIENCE (LOW DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'resilience', 'leadership', 'low', 'Tell me about a time when you faced significant business pressure.', 'Score 6: Candidate demonstrates executive presence. They describe a moment of high stakes where they maintained a focus on core objectives while managing a multitude of internal and external stressors.'),
('behavioral', 'resilience', 'leadership', 'low', 'Describe how you handle high-stakes negotiations that don’t go as planned.', 'Score 6: Strategic flexibility. Candidate explains how they managed the fallout without losing long-term leverage, showing the ability to pivot to a "Plan B" without emotional volatility.'),
('behavioral', 'resilience', 'leadership', 'low', 'How do you maintain composure during board-level discussions?', 'Score 6: Professional poise. Focus on active listening, delivering data-backed rebuttals calmly, and the ability to handle aggressive cross-examination from board members.'),
('behavioral', 'resilience', 'leadership', 'low', 'Tell me about a time when quarterly results were below expectations.', 'Score 6: Radical accountability. Candidate shows they took full ownership, provided a clear explanation for the variance, and led the immediate corrective action plan.'),
('behavioral', 'resilience', 'leadership', 'low', 'Describe how you manage stress during major transitions.', 'Score 6: Operational stability. Candidate describes a system for self-regulation and ensuring that their personal stress did not leak into the team’s performance or morale.'),
('behavioral', 'resilience', 'leadership', 'low', 'How do you recover after losing a large enterprise client?', 'Score 6: Resilience as a business process. Candidate describes the post-mortem, the steps to secure the remaining portfolio, and the immediate pivot to the high-value pipeline.'),
('behavioral', 'resilience', 'leadership', 'low', 'Tell me about a time when a strategic initiative failed.', 'Score 6: Learning agility. Focus on the ability to extract systemic insights from the failure and how they applied those insights to prevent similar losses in the future.'),
('behavioral', 'resilience', 'leadership', 'low', 'Describe how you manage resilience during industry uncertainty.', 'Score 6: Visionary endurance. Candidate shows they maintained a "horizon focus," looking past the current volatility to keep the organization aligned with long-term goals.'),
('behavioral', 'resilience', 'leadership', 'low', 'How do you stay motivated after years in high-pressure roles?', 'Score 6: Sustainable leadership. Candidate describes their personal system for avoiding cynicism and maintaining a high-performance output through purpose and self-awareness.'),
('behavioral', 'resilience', 'leadership', 'low', 'Tell me about a time when you had to manage disappointment at a senior level.', 'Score 6: Executive maturity. Candidate shows they acknowledged the disappointment but moved rapidly to "Scenario Planning" to find the next path forward.');

-- ------------------------------------------------------------------------------------------------
-- 2. RESILIENCE (MEDIUM DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'resilience', 'leadership', 'medium', 'Tell me about a strategic decision that did not deliver expected outcomes.', 'Score 6: Logic-based pivot. Candidate describes the initial data, the reason for the shortfall, and the non-defensive way they adjusted the strategy mid-course.'),
('behavioral', 'resilience', 'leadership', 'medium', 'Describe a time when shareholders or senior leaders challenged your results.', 'Score 6: Conviction with evidence. Candidate shows they defended their position with data while remaining open to valid criticism and adjusting where necessary.'),
('behavioral', 'resilience', 'leadership', 'medium', 'How do you manage resilience when leading large teams through uncertainty?', 'Score 6: Organizational stewardship. Candidate demonstrates how they acted as a "Shield" for the team, maintaining focus on execution while navigating corporate fog.'),
('behavioral', 'resilience', 'leadership', 'medium', 'Tell me about a time when you had to absorb pressure to protect your team.', 'Score 6: Servant leadership. Describes a situation where they took heat from executive levels to give their team the space and psychological safety required to fix an issue.'),
('behavioral', 'resilience', 'leadership', 'medium', 'Describe how you handle public or visible professional setbacks.', 'Score 6: Narrative control. Candidate shows they addressed the setback transparently and provided a clear "Next Steps" roadmap that restored confidence.'),
('behavioral', 'resilience', 'leadership', 'medium', 'How do you rebuild organizational confidence after a failed initiative?', 'Score 6: Restorative leadership. Candidate describes specific communication strategies and early "mini-wins" used to shift the organizational energy back to positive momentum.'),
('behavioral', 'resilience', 'leadership', 'medium', 'Tell me about a time when long-term strategy conflicted with short-term results.', 'Score 6: Strategic harmony. Candidate explains the trade-off calculation and how they justified a short-term hit to ensure the long-term health of the business.'),
('behavioral', 'resilience', 'leadership', 'medium', 'Describe how you manage emotional fatigue in senior leadership roles.', 'Score 6: Emotional intelligence (EQ). Candidate identifies the signs of executive burnout and the specific habits or delegate structures they use to maintain consistent clarity.'),
('behavioral', 'resilience', 'leadership', 'medium', 'When do you pivot versus persist at an executive level?', 'Score 6: Decision framework. Candidate describes the specific KPIs or market signals they use to distinguish between "hard work required" and a "flawed strategy."'),
('behavioral', 'resilience', 'leadership', 'medium', 'Tell me about a time when you had to defend your strategy despite criticism.', 'Score 6: Resilient authority. Candidate demonstrates they stood by a vision that they knew was correct, using future-value modeling to bring critics on board.');

-- ------------------------------------------------------------------------------------------------
-- 3. RESILIENCE (HIGH DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'resilience', 'leadership', 'high', 'Tell me about a defining professional setback in your career.', 'Score 6: Transformative resilience. A deep, reflective answer showing how a major loss led to a fundamental improvement in their leadership philosophy or business ethics.'),
('behavioral', 'resilience', 'leadership', 'high', 'Describe a time when your leadership credibility was severely tested.', 'Score 6: Integrity under fire. Candidate shows they restored trust through extreme transparency and consistent delivery, rather than through PR or blameshifting.'),
('behavioral', 'resilience', 'leadership', 'high', 'How do you navigate resilience during economic downturns?', 'Score 6: Frugal innovation. Candidate describes the "Tough Calls" (layoffs, budget cuts) made with empathy and the strategic redirection used to survive the cycle.'),
('behavioral', 'resilience', 'leadership', 'high', 'Tell me about a situation where you had to make a difficult decision knowing it would impact morale.', 'Score 6: Principled pragmatism. Candidate shows they explained the "Hard Why" to the organization and provided a path for the team to reclaim their morale through success.'),
('behavioral', 'resilience', 'leadership', 'high', 'Describe a time when stepping back was more resilient than pushing forward.', 'Score 6: Strategic temperance. Focus on the wisdom to admit a plan was wrong or the market was ready to shift, and the decision to regroup for a more intelligent future effort.'),
('behavioral', 'resilience', 'leadership', 'high', 'How do you prevent cynicism after years of competitive pressure?', 'Score 6: Purpose-driven leadership. Candidate identifies their personal "Mission" and how it scales beyond simple financial metrics to keep them energized.'),
('behavioral', 'resilience', 'leadership', 'high', 'Tell me about a strategic risk that failed and what you learned.', 'Score 6: Risk management meta-learning. Candidate describes how they revised their Entire Risk Assessment Framework based on the post-mortem of a failed bold bet.'),
('behavioral', 'resilience', 'leadership', 'high', 'How do you sustain long-term personal and organizational resilience?', 'Score 6: Cultural resilience. Candidate shows how they have baked resilience into the company culture (e.g., blameless post-mortems, experimentation budgets).'),
('behavioral', 'resilience', 'leadership', 'high', 'Describe how you mentor others in developing resilience.', 'Score 6: Resilience multiplier. Candidate demonstrates an ability to teach younger leaders how to separate their self-worth from business outcomes and focus on process.'),
('behavioral', 'resilience', 'leadership', 'high', 'What has been the toughest leadership moment in your career, and how did you handle it?', 'Score 6: Ultimate maturity. A specific, high-stakes story that showcases the convergence of logic, empathy, and decisive action under extreme conditions.');

-- ------------------------------------------------------------------------------------------------
-- 4. COMMUNICATION (LOW DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'communication', 'leadership', 'low', 'Tell me about communicating vision to your team.', 'Score 6: Narrative translation. Candidate shows they turned a high-level strategic goal into an inspiring, relatable mission that every team member personally bought into.'),
('behavioral', 'communication', 'leadership', 'low', 'Describe presenting to senior executives.', 'Score 6: Executive brevity. Focus on leading with the "Bottom Line," addressing risks upfront, and providing clear options for decision-making.'),
('behavioral', 'communication', 'leadership', 'low', 'How do you simplify complex strategy?', 'Score 6: Clarity of thought. Candidate describes using analogies, visual frameworks, or "The Rule of Three" to ensure the strategy is memorable and actionable.'),
('behavioral', 'communication', 'leadership', 'low', 'Tell me about leading a large team meeting.', 'Score 6: Engagement orchestration. Candidate shows they can hold the attention of a large group while ensuring key voices are heard and alignment is confirmed.'),
('behavioral', 'communication', 'leadership', 'low', 'Describe delivering quarterly performance updates.', 'Score 6: Strategic reporting. Candidate shows they didn''t just read numbers, but told the "Story of the Quarter," connecting results to future strategy.'),
('behavioral', 'communication', 'leadership', 'low', 'How do you manage difficult conversations?', 'Score 6: De-escalation. Focus on using neutral language, focusing on behaviors over personality, and reaching a collaborative forward-looking agreement.'),
('behavioral', 'communication', 'leadership', 'low', 'Tell me about aligning leadership teams.', 'Score 6: Horizontal influence. Candidate describes identifying the incentives of other departments and finding the "Common Ground" that allows them to collaborate.'),
('behavioral', 'communication', 'leadership', 'low', 'Describe managing stakeholder expectations.', 'Score 6: Scope discipline. Candidate shows they communicated boundaries early and honestly, preventing future disappointment by managing current reality.'),
('behavioral', 'communication', 'leadership', 'low', 'How do you communicate across global teams?', 'Score 6: Cultural and logisitical agility. Candidate describes adjusting for time-zones, language nuances, and digital communication norms to ensure inclusivity.'),
('behavioral', 'communication', 'leadership', 'low', 'Tell me about maintaining executive presence.', 'Score 6: Confidence and composure. Candidate explains their method for projecting calm authority in high-stakes environments through preparation and body language.');

-- ------------------------------------------------------------------------------------------------
-- 5. COMMUNICATION (MEDIUM DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'communication', 'leadership', 'medium', 'Tell me about leading communication during major change.', 'Score 6: Change management. Candidate describes a "Communication Cadence" that suppressed rumors and provided a sense of stability during a transition.'),
('behavioral', 'communication', 'leadership', 'medium', 'Describe influencing C-level stakeholders.', 'Score 6: Strategic alignment. Candidate speaks about "Business Case" logic and how they tied their proposal to the CEO/CFO''s top priorities.'),
('behavioral', 'communication', 'leadership', 'medium', 'How do you manage communication in mergers/acquisitions?', 'Score 6: Integration empathy. Focus on the balance between "Company Needs" and "Cultural Anxiety," and how they kept both teams productive through the shift.'),
('behavioral', 'communication', 'leadership', 'medium', 'Tell me about communicating during economic downturn.', 'Score 6: Radical transparency. Candidate shows they delivered the hard facts without sugar-coating, while providing a clear "Survival and Success" roadmap.'),
('behavioral', 'communication', 'leadership', 'medium', 'Describe handling high-visibility failures.', 'Score 6: Reputational repair. Candidate shows how they addressed the failure publicly (internal or external), took ownership, and defined the resolution.'),
('behavioral', 'communication', 'leadership', 'medium', 'How do you balance optimism and realism?', 'Score 6: The Stockdale Paradox. Candidate shows they can acknowledge the brutal facts of a situation while maintaining an unwavering belief in the ultimate victory.'),
('behavioral', 'communication', 'leadership', 'medium', 'Tell me about managing reputation risks.', 'Score 6: Proactive crisis communication. Candidate explains how they detected a risk early and used targeted communication to "Neutralize" the issue before it escalated.'),
('behavioral', 'communication', 'leadership', 'medium', 'Describe communicating controversial decisions.', 'Score 6: Rational courage. Candidate shows they prioritized "Organizational Health" over popularity, explaining the logic so that even dissenters understood the decision.'),
('behavioral', 'communication', 'leadership', 'medium', 'How do you ensure leadership alignment?', 'Score 6: Governance. Mentions use of "Steering Committees" or "Shared KPIs" that force communication and alignment across the top level of the company.'),
('behavioral', 'communication', 'leadership', 'medium', 'Tell me about communicating long-term transformation.', 'Score 6: Endurance messaging. Candidate describes how they kept the "Transformation Story" alive over months/years, preventing change fatigue through consistent updates.');

-- ------------------------------------------------------------------------------------------------
-- 6. COMMUNICATION (HIGH DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'communication', 'leadership', 'high', 'Tell me about shaping company-wide narrative.', 'Score 6: Cultural architect. Candidate describes how they helped define the "Core Identity" of the company and used it to drive performance across thousands of people.'),
('behavioral', 'communication', 'leadership', 'high', 'Describe defending strategy under public scrutiny.', 'Score 6: External presence. Focus on the ability to remain calm and logical during media inquiries, investor calls, or industry conferences.'),
('behavioral', 'communication', 'leadership', 'high', 'How do you influence board-level decision-making?', 'Score 6: Political stewardship. Candidate describes the "Pre-meeting" work—aligning individual board members privately before the final vote.'),
('behavioral', 'communication', 'leadership', 'high', 'Tell me about communicating during corporate crisis.', 'Score 6: Crisis Commander. Candidate describes acting as a single, calm source of truth during a PR disaster or operational collapse.'),
('behavioral', 'communication', 'leadership', 'high', 'Describe leading communication across international markets.', 'Score 6: Global CQ. Candidate shows they adjusted the brand story or corporate message to resonate with vastly different cultural and market realities.'),
('behavioral', 'communication', 'leadership', 'high', 'How do you rebuild trust after large-scale failure?', 'Score 6: Accountability and consistency. Focus on the long-term (12+ month) communication plan used to prove through actions that the company had changed.'),
('behavioral', 'communication', 'leadership', 'high', 'Tell me about managing communication with investors.', 'Score 6: Financial narrative. Candidate explains how they communicated "Value" rather than just "Profits," managing market expectations through strategic honesty.'),
('behavioral', 'communication', 'leadership', 'high', 'Describe aligning diverse executive opinions.', 'Score 6: Radical facilitation. Candidate describes a moment where they brought together a fractured C-Suite and forced a logical consensus for the good of the company.'),
('behavioral', 'communication', 'leadership', 'high', 'How do you sustain credibility over decades?', 'Score 6: Legacy integrity. Candidate shows how they maintained a consistent "Do-as-I-say" track record across multiple companies and roles.'),
('behavioral', 'communication', 'leadership', 'high', 'Tell me about mentoring future leaders in executive communication.', 'Score 6: Mentorship multiplier. Candidate demonstrates they can teach the nuance of things like "Presence," "Brevity," and "Strategic Diplomacy" to the next generation.');

-- ------------------------------------------------------------------------------------------------
-- 7. ADAPTABILITY (LOW DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'adaptability', 'leadership', 'low', 'Tell me about adapting to board-level expectations.', 'Score 6: Stakeholder agility. Candidate shows they adjusted their reporting style and strategic focus to align with a new board mandate or a shift in investor sentiment.'),
('behavioral', 'adaptability', 'leadership', 'low', 'Describe adjusting long-term vision due to market trends.', 'Score 6: Visionary pivot. Candidate explains the market signal they noticed and how they updated the 3-year roadmap to ensure future relevance.'),
('behavioral', 'adaptability', 'leadership', 'low', 'How do you respond to leadership transitions?', 'Score 6: Continuity with change. Candidate shows they maintained department stability while proactively looking for ways to support the new leader''s agenda.'),
('behavioral', 'adaptability', 'leadership', 'low', 'Tell me about managing evolving stakeholder demands.', 'Score 6: Priority triage. Candidate describes how they re-negotiated the "Strategic Order of Operations" when new, high-priority demands entered the picture.'),
('behavioral', 'adaptability', 'leadership', 'low', 'Describe adapting during rapid growth phases.', 'Score 6: Scalability. Candidate shows they identified which parts of the organization were "Breaking" under the weight of growth and pivoted to more mature processes.'),
('behavioral', 'adaptability', 'leadership', 'low', 'How do you respond to declining revenue periods?', 'Score 6: Adaptive frugality. Candidate describes shifting from "Growth mode" to "Efficiency mode" without losing the long-term strategic intent.'),
('behavioral', 'adaptability', 'leadership', 'low', 'Tell me about navigating organizational restructuring.', 'Score 6: Structural agility. Candidate shows they focused on where they could add the most value in the "New World" rather than clinging to their old title or department.'),
('behavioral', 'adaptability', 'leadership', 'low', 'Describe adjusting executive priorities.', 'Score 6: Strategic focus. Candidate shows they can kill a "Pet Project" to allocate resources to a newly discovered, higher-impact opportunity.'),
('behavioral', 'adaptability', 'leadership', 'low', 'How do you adapt across global markets?', 'Score 6: Global-local balance. Candidate describes adjusting the "Talk track" or "Go-to-Market" strategy to fit local cultural norms while maintaining global brand standards.'),
('behavioral', 'adaptability', 'leadership', 'low', 'Tell me about responding to emerging technologies.', 'Score 6: Tech curiosity. Candidate shows they didn''t just ignore a new trend but created a small "Task Force" to experiment with it (e.g., AI integration).');

-- ------------------------------------------------------------------------------------------------
-- 8. ADAPTABILITY (MEDIUM DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'adaptability', 'leadership', 'medium', 'Tell me about leading transformation initiatives.', 'Score 6: Holistic transformation. Candidate describes changing not just the "Tech" but the "People" and "Process" to ensure the transformation stuck.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'Describe adapting strategy during crisis.', 'Score 6: Crisis agility. Candidate shows they threw away the "Yearly Plan" to focus on the "Survival Plan" while identifying an opportunity the crisis created.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'How do you manage large-scale digital disruption?', 'Score 6: Digital evolution. Candidate describes how they dismantled a legacy manual process to adopt a disruptive technology that gave them a 10x speed advantage.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'Tell me about pivoting corporate direction.', 'Score 6: Decisive pivot. Candidate explains the data that forced the pivot and the logical communication used to bring the whole organization along.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'Describe adapting to investor expectations.', 'Score 6: Capital agility. Candidate shows they adjusted the business model (e.g. from Growth to Profitability) to meet the changing requirements of the capital markets.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'How do you manage strategic uncertainty?', 'Score 6: Scenario planning. Candidate describes creating multiple "If-Then" pathways rather than relying on a single, fragile 5-year plan.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'Tell me about balancing innovation and operational control.', 'Score 6: Ambidextrous leadership. Candidate shows they created a "Safe Zone" for new ideas that didn''t threaten the stable core of the business.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'Describe adapting governance models.', 'Score 6: Governance agility. Candidate shows they realized the current decision-making process was too slow and redesigned it to be more agile/decentralized.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'How do you adjust leadership approach across generations?', 'Score 6: Generational empathy. Candidate describes how they changed their communication and management style to resonate with Gen Z vs Boomers without losing authority.'),
('behavioral', 'adaptability', 'leadership', 'medium', 'Tell me about building an agile organization.', 'Score 6: Cultural agility. Candidate describes the specific policies (e.g. cross-functional squads, fail-fast budgets) they introduced to increase organizational speed.');

-- ------------------------------------------------------------------------------------------------
-- 9. ADAPTABILITY (HIGH DIFFICULTY - LEADERSHIP)
-- ------------------------------------------------------------------------------------------------
INSERT INTO public.assessment_questions (category, driver, experience_band, difficulty, question_text, evaluation_rubric) VALUES
('behavioral', 'adaptability', 'leadership', 'high', 'Tell me about redefining your company’s direction.', 'Score 6: Foundational shift. A massive story where the candidate recognized the industry was moving and successfully steered a large organization into a new category.'),
('behavioral', 'adaptability', 'leadership', 'high', 'Describe leading adaptation during industry collapse.', 'Score 6: Survival-to-Pivot. Focus on the cold logic used to exit a dying market and the visionary luck/skill used to enter a growing one simultaneously.'),
('behavioral', 'adaptability', 'leadership', 'high', 'How do you make decisions when long-term future is unclear?', 'Score 6: Decision-making. Candidate explains their heuristic for "Making the least-wrong decision" and building in "Reversibility" into every strategic bet.'),
('behavioral', 'adaptability', 'leadership', 'high', 'Tell me about navigating global economic crises.', 'Score 6: Macro-agility. Candidate shows they anticipated the shift (inflation, supply chain collapse) and had the organization hedged/ready before the impact.'),
('behavioral', 'adaptability', 'leadership', 'high', 'Describe reshaping culture to match future strategy.', 'Score 6: Identity architect. Candidate shows they changed the "Core Values" of the company to drive a new set of behaviors required for a new strategy.'),
('behavioral', 'adaptability', 'leadership', 'high', 'How do you handle radical transformation resistance?', 'Score 6: Change physics. Candidate describes identifying the "Inertia" in the company and the specific leverage points used to break it and move forward.'),
('behavioral', 'adaptability', 'leadership', 'high', 'Tell me about exiting a legacy model to adopt innovation.', 'Score 6: Cannibalization logic. Candidate shows they were willing to "Kill their own product" to launch a better, future-proof version, despite hitting short-term revenue.'),
('behavioral', 'adaptability', 'leadership', 'high', 'Describe sustaining adaptability across decades.', 'Score 6: Lifelong learning. Candidate describes their personal system for staying relevant as the world shifted from Analog to Digital to AI, and how they apply that to leadership.'),
('behavioral', 'adaptability', 'leadership', 'high', 'How do you build succession-ready adaptive leaders?', 'Score 6: Multiplier effect. Candidate demonstrates they have a system for identifying "Adaptive Potential" in their directs and coaching it into "Adaptive Leadership."'),
('behavioral', 'adaptability', 'leadership', 'high', 'Tell me about your toughest strategic pivot.', 'Score 6: Ultimate agility. A high-stakes, high-emotions story where they turned a potential corporate "Dead End" into a new, thriving 10-year growth path.');
